---
name: Continuous Integration (CI)

on:
  push:
  pull_request:

jobs:
  static-checks:
    name: Static checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: pip install gdtoolkit
      - uses: Scony/godot-gdscript-toolkit@4.3.0
        with:
          version: 4.3.0
      - run: gdformat --check scenes/
      - run: gdlint scenes/
